// Auto-generated luxury editorial fallback dataset
export const FALLBACK_CATEGORIES = [
  {
    "id": "cat_haute_couture",
    "name": "Haute Couture",
    "slug": "haute-couture",
    "description": "Exclusive custom-fitted high fashion directly from Paris and Milan ateliers.",
    "cover_image": "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    "sort_order": 1
  },
  {
    "id": "cat_runway",
    "name": "Runway & Seasons",
    "slug": "runway-seasons",
    "description": "Front-row analysis and seasonal breakdowns from the Big Four fashion weeks.",
    "cover_image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    "sort_order": 2
  },
  {
    "id": "cat_street_style",
    "name": "Street Style",
    "slug": "street-style",
    "description": "Metropolitan street aesthetics, oversized tailored chic, and urban avant-garde.",
    "cover_image": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80",
    "sort_order": 3
  },
  {
    "id": "cat_quiet_luxury",
    "name": "Quiet Luxury",
    "slug": "quiet-luxury",
    "description": "Understated elegance, artisanal cashmere, neutral tones, and timeless tailoring.",
    "cover_image": "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80",
    "sort_order": 4
  },
  {
    "id": "cat_sustainable",
    "name": "Sustainable Atelier",
    "slug": "sustainable-atelier",
    "description": "Circular couture, organic deadstock silks, and ethical luxury innovations.",
    "cover_image": "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80",
    "sort_order": 5
  },
  {
    "id": "cat_accessories",
    "name": "Accessories & Jewels",
    "slug": "accessories-jewels",
    "description": "Sculptural bags, archival vintage jewelry, and runway statement footwear.",
    "cover_image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    "sort_order": 6
  }
];

export const FALLBACK_TICKER = [
  {
    "id": "tck_1",
    "headline": "PARIS HAUTE COUTURE WEEK: DRAMATIC SCULPTURAL SILHOUETTES CAPTIVATE FRONT ROW",
    "tag": "BREAKING",
    "is_active": 1,
    "sort_order": 1
  },
  {
    "id": "tck_2",
    "headline": "SPRING/SUMMER 2026 FORECAST: THE ASCENT OF TRANSPARENT SILK ORGANZA & BUTTER YELLOW",
    "tag": "TREND REPORT",
    "is_active": 1,
    "sort_order": 2
  },
  {
    "id": "tck_3",
    "headline": "GUEST VOICES: HOW INDEPENDENT ATELIERS ARE DISRUPTING HERITAGE LUXURY HOUSES",
    "tag": "EXCLUSIVE",
    "is_active": 1,
    "sort_order": 3
  },
  {
    "id": "tck_4",
    "headline": "MILAN DIARIES: REFINED LEATHER CRAFTSMANSHIP MEETS FLUID GENDERLESS TAILORING",
    "tag": "RUNWAY",
    "is_active": 1,
    "sort_order": 4
  }
];

export const FALLBACK_SETTINGS = [
  {
    "key": "site_title",
    "value": "ZAIB ATTIRE"
  },
  {
    "key": "site_tagline",
    "value": "The Haute Editorial of Contemporary Runway & Fashion Culture"
  },
  {
    "key": "editor_in_chief",
    "value": "Camille de Valois"
  },
  {
    "key": "editorial_quote",
    "value": "Fashion is not merely what we drape upon the body; it is the visual cadence of modern thought, ambition, and artistic rebellion."
  },
  {
    "key": "guest_posting_enabled",
    "value": "true"
  },
  {
    "key": "contact_email",
    "value": "editorial@zaibattire.com"
  },
  {
    "key": "instagram_handle",
    "value": "@zaibattire_official"
  },
  {
    "key": "google_sheets_webhook_url",
    "value": "https://script.google.com/macros/s/AKfycbw3K_zX1MIk3bWQWyMuujRL4g0rso2NMuKFL2vTlDYCwJBtVN9OL2oVSem2begRveM6/exec"
  }
];

export const FALLBACK_POSTS = [
  {
    "id": "post_01",
    "title": "Architectural Drapery: How Sculptural Haute Couture is Redefining 2026 Runways",
    "slug": "architectural-drapery-haute-couture-2026",
    "subtitle": "From Daniel Roseberry at Schiaparelli to Parisian independent ateliers, garments are becoming wearable monuments.",
    "content": "## The Renaissance of Structural Form\n\nIn an era dominated by rapid algorithm-driven aesthetics, haute couture has retreated into its purest sanctuary: unapologetic, sculptural gravity. This season's runways in Paris proved that the silhouette is no longer obedient to the contours of anatomy—rather, fabric is treated like Carrara marble, engineered to hold impossible arches and cascading folds.\n\n### The Return of Heavy Silk Radzimir & Molded Corsetry\n\nAt Schiaparelli and Iris van Herpen, we witnessed garments that defy wind and gravity. Tailors are resurrecting archival techniques pioneered by Cristóbal Balenciaga in the late 1950s, using bonded silks, horsehair interlinings, and carbon-reinforced stays.\n\n> \"A dress must not merely fit the woman; it must construct a sovereign territory around her presence.\" — *Atelier Archive Notes, Place Vendôme*\n\n### Why the Trend is Sweeping Prêt-à-Porter\n\nWhile these structural masterpieces begin on the private runways of Avenue Montaigne, their architectural DNA is rapidly filtering into ready-to-wear:\n- **Exaggerated Shoulder Architecture**: Sharp, pagoda-style lines replacing traditional padded blazers.\n- **Cocoon Peplums**: Dramatic volume around the hips rendered in stiffened moiré.\n- **Curved Hemlines**: Asymmetrical knife-edge cuts that move with deliberate kinetic tempo.\n\nWhether worn at gala occasions or translated into dramatic evening tailoring, architectural drapery is a defiant statement of artistic permanence in an ephemeral digital age.",
    "cover_image": "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1600&q=85",
    "category_id": "cat_haute_couture",
    "category_name": "Haute Couture",
    "season": "Spring / Summer 2026",
    "read_time": "6 min read",
    "status": "published",
    "is_guest_post": 0,
    "is_featured": 1,
    "is_trending": 1,
    "views": 3845,
    "likes": 245,
    "tags": "[\"Schiaparelli\",\"Haute Couture\",\"Sculptural Fashion\",\"Paris Fashion Week\",\"Atelier\"]",
    "author_name": "Camille de Valois",
    "author_email": "admin@zaibattire.com",
    "author_bio": "Editor-in-Chief at ZAIB ATTIRE. Paris Fashion Week correspondent and luxury trend forecaster.",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://zaibattire.com",
    "author_social": "@camille_valois",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-04 16:50:53",
    "updated_at": "2026-10-04 16:50:53"
  },
  {
    "id": "post_02",
    "title": "The Evolution of Quiet Luxury: Why Muted Tactility Beats Loud Logos Every Time",
    "slug": "evolution-of-quiet-luxury-muted-tactility",
    "subtitle": "The second wave of quiet luxury is not boring beige—it is raw cashmere, untreated linen, and sensory opulence.",
    "content": "## Beyond the Sea of Beige\n\nWhen the \"Quiet Luxury\" wave first conquered editorial pages, critics predicted it would quickly devolve into sterile minimalism. They were mistaken. What we are seeing in late 2026 is an enriched iteration: **Sensory Maximalism hidden within Minimalist Shapes**.\n\n### The Anatomy of Silent Elegance\n\nTrue connoisseurs don't look for monogram prints; they look for the tension of hand-stitched pick seams and double-faced vicuña wool.\n\n- **Weightless Warmth**: Unlined double-cashmere coats that drape like dressing gowns.\n- **Subtle Earthy Palettes**: Slate gray, raw umber, bitter chocolate, and salted cream.\n- **The Whisper of Craft**: Polished horn buttons, unseen silk-bound armholes, and artisanal millings from Biella, Italy.\n\nWhen your wardrobe relies on pure fabric integrity, confidence shifts from looking expensive to feeling utterly serene.",
    "cover_image": "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80",
    "category_id": "cat_quiet_luxury",
    "category_name": "Quiet Luxury",
    "season": "Fall / Winter 2026",
    "read_time": "5 min read",
    "status": "published",
    "is_guest_post": 0,
    "is_featured": 0,
    "is_trending": 1,
    "views": 2910,
    "likes": 184,
    "tags": "[\"Minimalism\",\"The Row\",\"Loro Piana\",\"Cashmere\",\"Quiet Luxury\"]",
    "author_name": "Camille de Valois",
    "author_email": "admin@zaibattire.com",
    "author_bio": "Editor-in-Chief at ZAIB ATTIRE. Paris Fashion Week correspondent.",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://zaibattire.com",
    "author_social": "@camille_valois",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-04 16:50:53",
    "updated_at": "2026-10-04 16:50:53"
  },
  {
    "id": "post_03",
    "title": "Street Style Matrix: Tokyo to Milan — The Oversized Tailoring Phenomenon",
    "slug": "street-style-matrix-tokyo-milan-oversized-tailoring",
    "subtitle": "Guest Contributor Julian Vance breaks down how street fashion tastemakers are dismantling rigid formalwear.",
    "content": "## The Sidewalk as the Ultimate Runway\n\n*(Guest Contribution)*\n\nNowhere is the dialogue between runway fantasy and real-world expression more vibrant than on the pavement outside fashion week venues. Over the past three seasons, the defining garment of urban elegance has shifted decisively from sneakers to **subversive power suits**.\n\n### The Harajuku-Milan Nexus\n\nIn Tokyo's Shibuya crossing and Milan's Via Montenapoleone, the formula is clear:\n1. **Four-button double-breasted jackets** bought two sizes too large.\n2. **Puddle trousers** pooling nonchalantly over pointed-toe loafers or platform boots.\n3. **Contrast Layering**: Wearing an ultra-fine ribbed silk tank under an imposing worsted wool coat.\n\nThe oversized silhouette provides an armor against city chaos while whispering effortless nonchalance. It is tailoring liberated from the corporate boardroom.",
    "cover_image": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    "category_id": "cat_street_style",
    "category_name": "Street Style",
    "season": "Resort 2026",
    "read_time": "7 min read",
    "status": "published",
    "is_guest_post": 1,
    "is_featured": 0,
    "is_trending": 1,
    "views": 1853,
    "likes": 130,
    "tags": "[\"Streetwear\",\"Tokyo Fashion\",\"Harajuku\",\"Tailoring\",\"Guest Article\"]",
    "author_name": "Julian Vance",
    "author_email": "julian.vance@fashionpress.co",
    "author_bio": "Guest Contributor & Street Culture Photographer based between Tokyo and Berlin.",
    "author_avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://julianvance.photo",
    "author_social": "@julianvance_lens",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-04 16:50:53",
    "updated_at": "2026-10-04 16:50:53"
  },
  {
    "id": "post_04",
    "title": "Sustainable Silks & Biotech Leather: Inside the Ethical Couture Revolution",
    "slug": "sustainable-silks-biotech-leather-ethical-couture",
    "subtitle": "How lab-grown mycelium and cruelty-free peace silk are changing luxury houses from the roots up.",
    "content": "## The Future of Luxury is Bio-Fabricated\n\nFor decades, the luxury sector claimed that synthetic alternatives could never match the hand-feel and patina of calfskin or mulberry silk. That barrier has now dissolved.\n\nLeading ateliers are collaborating with bio-engineers to produce mycelium mushroom hides that age with equal nobility to Tuscan bridle leather. Meanwhile, cellular silk farms in Switzerland yield gossamer filaments with tensile strength greater than steel, without harming a single silkworm.\n\nLuxury in 2026 is no longer defined by rarity through exploitation—it is defined by genius, stewardship, and ecological reverence.",
    "cover_image": "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1200&q=80",
    "category_id": "cat_sustainable",
    "category_name": "Sustainable Atelier",
    "season": "Spring / Summer 2026",
    "read_time": "4 min read",
    "status": "published",
    "is_guest_post": 0,
    "is_featured": 0,
    "is_trending": 0,
    "views": 1221,
    "likes": 98,
    "tags": "[\"Sustainability\",\"Biotech\",\"Mycelium\",\"Cruelty Free\",\"Innovation\"]",
    "author_name": "Elena Rostova",
    "author_email": "elena@zaibattire.com",
    "author_bio": "Senior Materials Editor and Sustainable Textile Researcher.",
    "author_avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://zaibattire.com",
    "author_social": "@elena_textiles",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-04 16:50:53",
    "updated_at": "2026-10-04 16:50:53"
  },
  {
    "id": "post_05",
    "title": "Sculptural Footwear & The Return of Architectural Heels",
    "slug": "sculptural-footwear-architectural-heels",
    "subtitle": "Loewe, Alaïa, and Jacquemus prove that shoes are this year’s most collectible modern art.",
    "content": "## Footwear as Kinetic Sculpture\n\nStep away from conventional stilettos. The accessories conversation is currently dominated by heels sculpted into brass globes, cantilevered arches, and molten metallic drips.\n\nAlaïa's mesh ballet flats and Loewe's surrealist heels have transformed shoes into conversation starters that anchor minimalist monochrome ensembles. When your footwear carries museum-worthy lines, the rest of your outfit can speak in an elegant murmur.",
    "cover_image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    "category_id": "cat_accessories",
    "category_name": "Accessories & Jewels",
    "season": "Fall / Winter 2026",
    "read_time": "5 min read",
    "status": "published",
    "is_guest_post": 0,
    "is_featured": 0,
    "is_trending": 0,
    "views": 1421,
    "likes": 112,
    "tags": "[\"Shoes\",\"Alaïa\",\"Footwear\",\"Accessories\",\"Runway\"]",
    "author_name": "Camille de Valois",
    "author_email": "admin@zaibattire.com",
    "author_bio": "Editor-in-Chief at ZAIB ATTIRE.",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://zaibattire.com",
    "author_social": "@camille_valois",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-04 16:50:53",
    "updated_at": "2026-10-04 16:50:53"
  },
  {
    "id": "post_guest_1791133726611",
    "title": "Velvet Reverie",
    "slug": "velvet-reverie-6612",
    "subtitle": "Guest editorial piece on ZAIB ATTIRE.",
    "content": "Velvet on the Runway",
    "cover_image": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    "category_id": null,
    "category_name": "Haute Couture",
    "season": "Spring / Summer 2026",
    "read_time": "1 min read",
    "status": "published",
    "is_guest_post": 1,
    "is_featured": 0,
    "is_trending": 1,
    "views": 5,
    "likes": 0,
    "tags": "[]",
    "author_name": "Helena Vance",
    "author_email": "helena@vogueparis.fr",
    "author_bio": "Guest Fashion Contributor at ZAIB ATTIRE",
    "author_avatar": "https://api.dicebear.com/7.x/initials/svg?seed=Helena%20Vance&backgroundColor=0f0f11&textColor=d4af37",
    "author_website": "",
    "author_social": "",
    "guest_submission_id": "gsub_1791133690367_bea527",
    "editorial_notes": null,
    "created_at": "2026-10-04 17:08:46",
    "updated_at": "2026-10-04 17:08:46"
  },
  {
    "id": "post_1791217948305_4658",
    "title": "hd",
    "slug": "dhd",
    "subtitle": "",
    "content": "fdhd",
    "cover_image": "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
    "category_id": null,
    "category_name": "Runway & Seasons",
    "season": "Spring / Summer 2026",
    "read_time": "1 min read",
    "status": "published",
    "is_guest_post": 0,
    "is_featured": 0,
    "is_trending": 0,
    "views": 1,
    "likes": 0,
    "tags": "[]",
    "author_name": "Camille de Valois",
    "author_email": "admin@modaetoile.com",
    "author_bio": "Editor-in-Chief at MODA ÉTOILE.",
    "author_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    "author_website": "https://modaetoile.com",
    "author_social": "@camille_valois",
    "guest_submission_id": null,
    "editorial_notes": null,
    "created_at": "2026-10-05 16:32:28",
    "updated_at": "2026-10-05 16:32:28"
  },
  {
    "id": "post_guest_1791220173146",
    "title": "The Structural Revival of Corsetry in Contemporary Streetwear",
    "slug": "the-structural-revival-of-corsetry-in-contemporary-streetwear-3146",
    "subtitle": "An exploration of deconstructed corsetry and urban silhouettes",
    "content": "Corsetry has historically functioned as both constriction and armor...",
    "cover_image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    "category_id": null,
    "category_name": "Streetwear & Subculture",
    "season": "Spring / Summer 2026",
    "read_time": "1 min read",
    "status": "published",
    "is_guest_post": 1,
    "is_featured": 0,
    "is_trending": 1,
    "views": 1,
    "likes": 0,
    "tags": "[\"corsetry\",\"streetwear\",\"berlin\"]",
    "author_name": "Elena Rostova",
    "author_email": "elena@berlin-couture.de",
    "author_bio": "Fashion critic and archival archivist in Berlin",
    "author_avatar": "https://api.dicebear.com/7.x/initials/svg?seed=Elena%20Rostova&backgroundColor=0f0f11&textColor=d4af37",
    "author_website": "https://elenarostova.de",
    "author_social": "",
    "guest_submission_id": "ZAIB-GUEST-5303",
    "editorial_notes": null,
    "created_at": "2026-10-05 17:09:33",
    "updated_at": "2026-10-05 17:09:33"
  }
];
